server:
  port: 8101
spring:
  application:
    name: dubbo-consumer
dubbo:
  registry:
    address: zookeeper://192.168.222.154:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 28101
  consumer:
    application: dubbo-consumer
    #启动应用时是否检查注册中心上有没有依赖的服务，默认true
    check: false
    retries: 3
    stub: com.it.impl.UserServiceStub
    version: 3
#    timeout: 500